-- require("hover").setup {
--   init = function()
--     -- Load providers for hover
--     require("hover.providers.lsp")        -- LSP-based hover
--     require("hover.providers.diagnostic") -- Diagnostic hover
--   end,
--   preview_opts = {
--     border = 'rounded',   -- Use 'rounded', 'solid', 'double', or 'shadow' for better visuals
--     winblend = 10         -- Add transparency to the hover window
--   },
--   preview_window = false, -- Disable separate preview window
--   title = true,           -- Display a title in the hover pane
--   mouse_providers = {
--     'LSP',                -- Enable hover with mouse for LSP
--     'diagnostic'          -- Enable hover with mouse for diagnostics
--   },
--   mouse_delay = 500       -- Reduce mouse hover delay
-- }
--
-- -- Keymaps for hover actions
-- vim.keymap.set("n", "K", require("hover").hover, { desc = "hover.nvim" })
-- vim.keymap.set("n", "gK", require("hover").hover_select, { desc = "hover.nvim (select)" })
-- vim.keymap.set("n", "<C-p>", function() require("hover").hover_switch("previous") end,
--   { desc = "hover.nvim (previous source)" })
-- vim.keymap.set("n", "<C-n>", function() require("hover").hover_switch("next") end,
--   { desc = "hover.nvim (next source)" })
--

