-- local opts = {
--   providers = {
--     "lsp",
--     "treesitter",
--     "regex",
--   },
--   delay = 100,
--   filetypes_denylist = {
--     "dirbuf",
--     "dirvish",
--     "fugitive",
--   },
--   under_cursor = true,
--   large_file_cutoff = 10000,
--   large_file_overrides = nil,
--   min_count_to_highlight = 1,
--   should_enable = function(bufnr) return true end,
--   case_insensitive_regex = false,
--   disable_keymaps = false,
-- }
--
--
-- vim.api.nvim_set_keymap("n", "]r", "<cmd>lua require('illuminate').goto_next_reference()<CR>",
--   { noremap = true, silent = true })
-- vim.api.nvim_set_keymap("n", "[r", "<cmd>lua require('illuminate').goto_prev_reference()<CR>",
--   { noremap = true, silent = true })
--
-- return opts
