-- local lspconfig = require("lspconfig")
-- local mason_lspconfig = require("mason-lspconfig")
-- local util = require("lspconfig.util")
--
-- -- 1. Setup Mason
-- require("mason").setup()
--
-- -- 2. Khai báo capabilities (nên giữ nguyên như bạn đã làm)
-- local capabilities = require("blink.cmp").get_lsp_capabilities()
--
-- -- 3. Hàm on_attach chung (Sử dụng cho tất cả LSP)
-- local function on_attach(client, bufnr)
-- 	-- Kích hoạt illuminate cho highlight các biến/tham số
-- 	local status_ok, illuminate = pcall(require, "illuminate")
-- 	if status_ok then
-- 		illuminate.on_attach(client)
-- 	end
--
-- 	-- Cài đặt keymaps cho buffer cụ thể ở đây
-- 	-- Ví dụ: require("keymaps").lsp_attach(bufnr)
-- end
--
-- -- 4. Định nghĩa cấu hình mặc định (Handler)
-- -- Áp dụng cho TẤT CẢ các server do Mason cài đặt
-- mason_lspconfig.setup_handlers({
-- 	function(server_name)
-- 		-- Đặt cấu hình mặc định chung
-- 		local config = {
-- 			capabilities = capabilities,
-- 			on_attach = on_attach,
-- 			-- Định nghĩa signs cho diagnostics (Đã làm sạch và sử dụng ký tự bạn muốn)
-- 			diagnostics = {
-- 				signs = {
-- 					text = {
-- 						[vim.diagnostic.severity.ERROR] = "", -- Thay thế Ghost bằng ký tự phổ biến hơn
-- 						[vim.diagnostic.severity.WARN] = "",
-- 						[vim.diagnostic.severity.HINT] = "",
-- 						[vim.diagnostic.severity.INFO] = "",
-- 					},
-- 					line_text = {
-- 						[vim.diagnostic.severity.ERROR] = "E",
-- 						[vim.diagnostic.severity.WARN] = "W",
-- 					},
-- 				},
-- 			},
-- 		}
--
-- 		-- Kích hoạt cấu hình mặc định
-- 		lspconfig[server_name].setup(config)
-- 	end,
-- })
--
-- -- 5. Cấu hình các server cụ thể cần tùy chỉnh ĐẶC BIỆT
-- -- (Sử dụng lspconfig.SERVER_NAME.setup() để ghi đè hoặc bổ sung)
--
-- -- Cấu hình Lua (dùng .setup thay vì ghi đè vim.lsp.config.lua_ls)
-- lspconfig.lua_ls.setup({
-- 	capabilities = capabilities,
-- 	on_attach = on_attach,
-- 	settings = {
-- 		Lua = {
-- 			runtime = { version = "LuaJIT" },
-- 			diagnostics = {
-- 				globals = { "vim" },
-- 				enable = true, -- Mặc định nên bật, sau đó có thể lọc
-- 				workspaceDelay = -1, -- Không chạy workspace diagnostics
-- 			},
-- 			workspace = {
-- 				library = vim.api.nvim_get_runtime_file("", true),
-- 				checkThirdParty = false, -- Nên tắt nếu không cần thiết để tăng tốc
-- 			},
-- 			hint = { enable = true },
-- 		},
-- 	},
-- })
--
-- -- Cấu hình Tailwind CSS (Quan trọng: Giải quyết vấn đề Monorepo)
-- lspconfig.tailwindcss.setup({
-- 	capabilities = capabilities,
-- 	on_attach = on_attach,
-- 	-- Thiết lập root_dir để chỉ khởi động LSP khi tìm thấy file config cụ thể
-- 	root_dir = util.root_pattern("tailwind.config.js", "tailwind.config.cjs", "tailwind.config.ts", "package.json"),
-- })
--
-- -- Cấu hình JSON LS (Tích hợp schemastore)
-- lspconfig.jsonls.setup({
-- 	capabilities = capabilities,
-- 	on_attach = on_attach,
-- 	settings = {
-- 		json = {
-- 			schemas = require("schemastore").json.schemas(),
-- 			validate = { enable = true },
-- 		},
-- 	},
-- })
--
-- -- Cấu hình Prisma LS
-- lspconfig.prismals.setup({
-- 	capabilities = capabilities,
-- 	on_attach = on_attach,
-- 	-- Nếu bạn dùng Prisma trong Monorepo, hãy đặt root_dir tìm file schema.prisma
-- 	root_dir = util.root_pattern("schema.prisma"),
-- })
--
-- -- 6. Ensure Installed (Nếu bạn chưa chạy Mason trước)
-- mason_lspconfig.setup({
-- 	ensure_installed = { "lua_ls", "html", "cssls", "prismals", "dockerls", "jsonls", "tailwindcss" },
-- 	automatic_installation = true,
-- })
