-- require("rest-nvim").setup({
-- 	-- Mở kết quả ở panel ngang (false để mở dọc)
-- 	result_split_horizontal = false,
-- 	result_split_in_place = false,
--
-- 	-- Tự động highlight JSON trong response
-- 	highlight = {
-- 		enabled = true,
-- 		timeout = 200,
-- 	},
--
-- 	-- Cấu hình cURL
-- 	skip_ssl_verification = true, -- Bỏ qua lỗi SSL nếu cần
--
-- 	result = {
-- 		split = {
-- 			in_place = false,
-- 			horizontal = false,
-- 			stay_in_current_window_after_split = true,
-- 		},
-- 		behavior = {
-- 			decode_url = true,
-- 			show_info = {
-- 				url = true,
-- 				headers = true,
-- 				http_info = true,
-- 				curl_command = true,
-- 			},
-- 			formatters = {
-- 				json = function(body)
-- 					-- Tìm phần JSON giữa # @_RES và # @_END
-- 					local json_body = body:match("# @_RES%s*(.-)%s*# @_END")
-- 					vim.notify("Extracted JSON: " .. (json_body or "nil"), vim.log.levels.INFO) -- Log trong Neovim
--
-- 					if json_body then
-- 						-- Format JSON với jq
-- 						local formatted_json = vim.fn.system("jq '.'", json_body)
-- 						if formatted_json then
-- 							return body:gsub(json_body, formatted_json) -- Thay thế JSON cũ
-- 						end
-- 					end
-- 					return body -- Nếu không tìm thấy JSON, giữ nguyên
-- 				end,
-- 				html = function(body)
-- 					if vim.fn.executable("tidy") == 0 then
-- 						return body, { found = false, name = "tidy" }
-- 					end
-- 					local fmt_body = vim.fn
-- 						.system({
-- 							"tidy",
-- 							"-i",
-- 							"-q",
-- 							"--tidy-mark",
-- 							"no",
-- 							"--show-body-only",
-- 							"auto",
-- 							"--show-errors",
-- 							"0",
-- 							"--show-warnings",
-- 							"0",
-- 							"-",
-- 						}, body)
-- 						:gsub("\n$", "")
--
-- 					return fmt_body, { found = true, name = "tidy" }
-- 				end,
-- 			},
-- 		},
-- 	},
-- })
--
-- vim.api.nvim_set_keymap("n", "<leader>rr", "<cmd>Rest run<CR>", { noremap = true, silent = true })
-- vim.api.nvim_set_keymap("n", "<leader>rl", "<cmd>Rest last<CR>", { noremap = true, silent = true })
-- vim.api.nvim_set_keymap("n", "<leader>rp", "<cmd>Rest preview<CR>", { noremap = true, silent = true })
--
-- vim.api.nvim_create_autocmd("BufReadPost", {
-- 	pattern = "rest_nvim_result",
-- 	callback = function()
-- 		vim.bo.modifiable = true
-- 		vim.cmd("%!jq .")
-- 	end,
-- })
