-- require('smear_cursor').setup({
--   -- cursor_color = '#326fa8',
--   -- stiffness = 0.3,
--   -- trailing_stiffness = 0.2,
--   -- smear_between_buffers = true,
--   distance_stop_animating = 0.0,
--   cursor_color = "#ff8800",
--   stiffness = 0.2,
--   trailing_stiffness = 0.1,
--   trailing_exponent = 5,
--   hide_target_hack = true,
--   gamma = 2,
-- })
--
-- vim.o.guicursor = "n-v-c:block-Cyan,i-ci:ver25-Red,r-cr:hor20-Green"
--
-- vim.api.nvim_set_hl(0, "Cursor", { bg = "#ff0000", fg = "#ffffff" }) -- Đỏ nền, trắng chữ
